In [74]:
import pandas as pd
import os 
import traceback
import json
import csv

# Virginia Job Postings

In [98]:
# The code below loads the processed CSV files for Virginia Open Data
file_list = [
'01openjobs-jobpostings.mar-2016.csv',
'02openjobs-jobpostings.apr-2016.csv',
'03openjobs-jobpostings.may-2016.csv',
'04openjobs-jobpostings.jun-2016.csv',
'05openjobs-jobpostings.jul-2016.csv',
'06openjobs-jobpostings.aug-2016.csv',
'07openjobs-jobpostings.sep-2016.csv',
'08openjobs-jobpostings.oct-2016.csv',
'09openjobs-jobpostings.nov-2016.csv',
'10openjobs-jobpostings.dec-2016.csv',
'11openjobs-jobpostings.jan-2017.csv',
'12openjobs-jobpostings.feb-2017.csv',
'13openjobs-jobpostings.mar-2017.csv',
'14openjobs-jobpostings.apr-2017.csv',
'15openjobs-jobpostings.may-2017.csv',
'16openjobs-jobpostings.jun-2017.csv',
'17openjobs-jobpostings.jul-2017.csv']

open_data = pd.DataFrame()
for filename in file_list:
    data = pd.read_csv(
        "/Users/kwheatley/Desktop/Capstone/virginia_job_postings_csv/" + filename)
    open_data = open_data.append(data)

In [181]:
open_data.to_csv("virginia_job_posts.csv")
open_data.head()

,Unnamed: 0,datePosted,organizationName,title,onetName,onetCode,numberOfOpenings,medianSalary,jobDescription,locality,region
0,0,2016-03-17,"1105 Media, Inc.",Media Consultant,Public Relations Specialists,27-3031.00,1,90000.0,Media consultant. Email. tweet. Location:Vienn...,Vienna,Virginia
1,0,2016-03-17,"1105 Media, Inc.",Social Media Intern,"Media and Communication Workers, All Other",27-3099.00,1,0.0,Social media intern. Email. tweet. Location:Vi...,Vienna,Virginia
2,0,2016-03-17,AAA Motor Club,Automotive Service Manager-Norfolk Car Care Ce...,Customer Service Representatives,43-4051.00,1,25000.0,Job Responsibilities. Primary Job Functions: m...,Norfolk,Virginia
3,0,2016-03-17,AAA Motor Club,Automotive Service Manager-Hampton Car Care Ce...,Customer Service Representatives,43-4051.00,1,19000.0,Job Responsibilities. Primary Job Functions: m...,Hampton,Virginia
4,0,2016-03-17,AAA Motor Club,Service Truck Operator-Norfolk,Not Classified,99-9999.00,1,0.0,"As a service truck operator, you will be requi...",Norfolk,Virginia

# Indeed Job Postings

In [50]:
# # This script takes the original json files and converts them into CSV

# datastore = []
# directory = '/Users/kwheatley/Desktop/Capstone/indeed_job_descriptions'
# for path, subdirs, file_list in os.walk(directory):  
#     for file in file_list:
#         if file != '.DS_Store':
#             try:
# #                 print("file:", file)
#                 for line in open(path + '/' + file, 'r'):
#                     datastore.append(json.loads(line))
#             except Exception as e:
#                 print(traceback.format_exc())
#                 continue
# 
# for record in datastore:
# #     print()
# #     print(record)
#     companyName = record['companyName']
#     try:
#         createdDate = record['createdDate']
#     except Exception as e:
#         createdDate = '1900-01-01'
#     daysCreatedBefore = record['daysCreatedBefore']
#     id = record['id']
#     location = record['location']
#     salary = record['salary']
#     scrapeTime = record['scrapeTime']
#     searchTerm = record['searchTerm']
#     summaryText = record['summaryText']
#     title = record['title']
#     url = record['url']
#     row = [companyName,createdDate,daysCreatedBefore,id,location,salary,scrapeTime,
#           searchTerm,summaryText,title,url]
#     with open("indeed_job_postings.csv", 'a') as myfile:
#         wr = csv.writer(myfile, quoting=csv.QUOTE_ALL)
#         wr.writerow(row)

In [94]:
indeed_data = pd.read_csv("indeed_job_postings.csv",header=None)
indeed_data.columns = ['company','created_date','days_created_before','id','location','salary','scrape_time',
          'search_term','summary_text','title','url']
indeed_data.head()

,company,created_date,days_created_before,id,location,salary,scrape_time,search_term,summary_text,title,url
0,Murdock Martell,2018-03-19T02:58:33,12,c54bc3126565a2b5,"Saratoga, CA 95070",Not_Found,1522490313,Accounting,We have an Accounting Manager opening with our...,Accounting Manager,https://www.indeed.com/m/viewjob?jk=c54bc31265...
1,SSL (Space Systems Loral),2018-03-30T02:58:35,1,7870c55efdd96581,"Palo Alto, CA 94303",Not_Found,1522490315,Accounting,SSL is seeking an Accounting Manager to manage...,Accounting Manager,https://www.indeed.com/m/viewjob?jk=7870c55efd...
2,Accounting Principals,2018-03-11T02:58:43,20,3595884323690603,"San Jose, CA 95110",Not_Found,1522490323,Accounting,Accounting Specialist Job in San Jose Are you...,Accounting Specialist,https://www.indeed.com/m/viewjob?jk=3595884323...
3,Interesse International Inc,2018-03-22T02:58:46,9,16d6225e941ef5f8,"San Jose, CA",Not_Found,1522490326,Accounting,- Manage / Responsible for daily accounting tr...,Accounting Manager,https://www.indeed.com/m/viewjob?jk=16d6225e94...
4,Hampton Inn Manhattan/Times Square South,2018-03-13T23:06:34,17,f141b703641cd1c7,"New York, NY 10018",Not_Found,1522476394,Accounting,"**Opportunity: Accounting Clerk** Verify, obt...",Accounting Clerk,https://www.indeed.com/m/viewjob?jk=f141b70364...

# Glassdoor Salaries

In [179]:
datastore = []
directory = '/Users/kwheatley/Downloads/tech-salary-project/salaries/'
for path, subdirs, file_list in os.walk(directory):  
    for file in file_list:
        if file != '.DS_Store':
            try:
#                 print("file:", file)
                json_data=open(path + '/' + file).read()
                records_list = json.loads(json_data)
                for record in records_list:
                    meanPay = record['meanPay']
                    jobTitle = record['jobTitle']
                    company = record['company']
                    row = [meanPay,jobTitle,company]                
                    
                    with open("glassdoor_salaries.csv", 'a') as myfile:
                        wr = csv.writer(myfile, quoting=csv.QUOTE_ALL)
                        wr.writerow(row)
            except Exception as e:
                print(path + '/' + file)
                print(traceback.format_exc())
                continue